auth:
  sessionSecret: "some good long random string" # Any strong random string for signing sessions
  openId:
    realm: https://accounts.google.com # Or some other realm
    clientId: "my id"
    clientSecret: "my secret"

server:
  port: 443
  address: localhost
  publicUrl: https://datastation.mydomain.com # The address users will enter into the browser to use the app
  tlsKey: /home/server/certs/datastation.key.pem # Can be left blank and set at the reverse-proxy level if desired
  tlsCert: /home/server/certs/datastation.cert.pem

database:
  address: localhost # Address of your PostgreSQL instance
  username: datastation # Should be a dedicated PostgreSQL user for DataStation
  password: "some good password"
  database: datastation # Should be a dedicated database within PostgreSQL for DataStation