#!/usr/bin/env bash

set -e

echo "package runner

// GENERATED BY ./runner/scripts/generate_program_type_info.sh. DO NOT MODIFY.

var packedProgramTypeInfo = map[SupportedLanguages]string{" > runner/program_info.go
for file in $(ls ./shared/languages/*.json); do
    echo "$(cat $file | jq '.id'): \`$(cat $file | jq -c '.')\`," >> runner/program_info.go
done

echo "}" >> runner/program_info.go

gofmt -w -s .
