name: Build and publish artifacts

on:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - run: ./scripts/ci/prepare_linux.sh
    - run: echo "GIT_TAG=`git tag --points-at HEAD`" >> $GITHUB_ENV
    - run: yarn release-desktop $GIT_TAG
    - name: Upload on release
      run: |
        curl \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./releases/linux-x64-$GIT_TAG.zip \
          "https://uploads.github.com/repos/multiprocessio/datastation/releases/$GIT_TAG/assets?name=linux-x64-$GIT_TAG.zip"

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - run: ./scripts/ci/prepare_macos.sh
    - run: echo "GIT_TAG=`git tag --points-at HEAD`" >> $GITHUB_ENV
    - run: yarn release-desktop $GIT_TAG
    - name: Upload release
      run: |
        curl \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./releases/darwin-x64-$GIT_TAG.zip \
          "https://uploads.github.com/repos/multiprocessio/datastation/releases/$GIT_TAG/assets?name=darwin-x64-$GIT_TAG.zip"

  build-windows:
    runs-on: windows-latest

    steps:
    - run: powershell ./scripts/ci/prepare_windows.ps
    - run: echo "GIT_TAG=`git tag --points-at HEAD`" >> $Env:GITHUB_ENV
    - run: yarn release-desktop $Env:GIT_TAG
    - name: Upload release
      run: |
        curl \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./releases/win32-x64-$Env:GITHUB_.zip \
          "https://uploads.github.com/repos/multiprocessio/datastation/releases/$Env:GIT_TAG/assets?name=win32-x64-$Env:GIT_TAG.zip"
